include .make/Makefile

vignettes/progressr-intro.md: OVERVIEW.md vignettes/incl/clean.css
	sed -i '/%\\Vignette/!d' $@
	echo "<!-- DO NOT EDIT THIS FILE! Edit 'OVERVIEW.md' instead and then rebuild this file with 'make vigs' -->" >> $@
	cat $< >> $@

vigs: vignettes/progressr-intro.md
